services:
    mongodb:
        image: mongo
        environment:
            MONGO_INITDB_ROOT_USERNAME: animalhouse
            MONGO_INITDB_ROOT_PASSWORD: animalhousepass
        ports:
            - 27017:27017

    postgresql:
        image: postgres
        environment:
            POSTGRES_DB: "security"
            POSTGRES_USER: "animalhouse"
            POSTGRES_PASSWORD: "animalhousepass"
        ports:
            - 5432:5432

    redis:
        image: redis
        command: redis-server --requirepass animalhousepass
        ports:
            - 6379:6379

    mail:
        image: mailhog/mailhog
        ports:
            - "1025:1025"
            - "8025:8025"


#    prometheus:
#        image: prom/prometheus
#        volumes:
#            - ./prometheus.yml:/etc/prometheus/prometheus.yml
#        ports:
#            - 9090:9090
#        command:
#            - '--config.file=/etc/prometheus/prometheus.yml'
#
#    grafana:
#        image: grafana/grafana
#        depends_on:
#            - prometheus
#        ports:
#            - 3000:3000
#        restart: always
#        environment:
#            GF_SECURITY_ADMIN_USERNAME: admin
#            GF_SECURITY_ADMIN_PASSWORD: admin
