global:
    scrape_interval:     5s
    evaluation_interval: 5s

scrape_configs:
    - job_name: prometheus
      static_configs:
          - targets:
                - localhost:8080
                - host.docker.internal:8080 # For connecting to a scrape endpoint from Prometheus running in a Docker container
